POST https://api.omise.co/sources
Authorization: Basic {{OMISE_PUBLIC_KEY}}
Content-Type: application/json

{
  "amount": 400000,
  "currency": "THB",
  "type": "promptpay"
}

###

POST https://api.omise.co/charges
Authorization: Basic {{OMISE_SECRET_KEY}}
Content-Type: application/json

{
  "amount": 400000,
  "currency": "THB",
  "source": "src_test_5tw0mhj9y5wuddqyxlz",
  "metadata": {},
  "expires_at": "promptpay"
}

###

POST https://api.omise.co/charges
Authorization: Basic {{OMISE_SECRET_KEY}}
Content-Type: application/json

{
  "amount": 400000,
  "currency": "THB",
  "source": {
    "type": "promptpay"
  },
  "metadata": {}
}

###

POST https://api.omise.co/charges/chrg_test_5tw0cmu2ni3uo0xnrv7/expire
Authorization: Basic {{OMISE_SECRET_KEY}}
Content-Type: application/json

###

POST https://api.omise.co/charges/chrg_test_5tw0mji0g2ywwt0jdzp/mark_as_paid
Authorization: Basic {{OMISE_SECRET_KEY}}
Content-Type: application/json

###

POST https://api.omise.co/charges/chrg_test_5tw0epjz89dpec12kcr/mark_as_failed
Authorization: Basic {{OMISE_SECRET_KEY}}
Content-Type: application/json

###

GET https://api.omise.co/charges/chrg_test_5tw096vj2y0tdpobijx
Authorization: Basic {{OMISE_SECRET_KEY}}
Content-Type: application/json

###

GET https://api.omise.co/charges
Authorization: Basic {{OMISE_SECRET_KEY}}
Content-Type: application/json

###

GET https://api.omise.co/account
Authorization: Basic {{OMISE_SECRET_KEY}}
Content-Type: application/json

###

GET https://api.omise.co/balance
Authorization: Basic {{OMISE_SECRET_KEY}}
Content-Type: application/json

###
