export const headNameChart = {
    soc: "soc",
    rangeToGo: "rangeToGo",
    speed: "speed",
    voltBatt: "voltBatt",
    motor1RPM: "motor1RPM",
    motor1Volt: "motor1Volt",
    motor1Current: "motor1Current",
    motor1Torque: "motor1Torque",
    motor2RPM: "motor2RPM",
    motor2Volt: "motor2Volt",
    motor2Current: "motor2Current",
    motor2Torque: "motor2Torque",
    motor3RPM: "motor3RPM",
    motor3Volt: "motor3Volt",
    motor3Current: "motor3Current",
    motor3Torque: "motor3Torque",
    acpMain: "acpMain",
    acpSub: "acpSub",
    ect1: "ect1",
    ect2: "ect2",
    stearing: "stearing",
    breakPos: "breakPos",
    gearPos: "gearPos",
    aBatt: "aBatt",
    errorMotor1: "errorMotor1",
    errorMotor2: "errorMotor2",
    errorMotor3: "errorMotor3",
    timestamp: "timestamp",
}

export const NameChart = {
    GraphAbatt: "GraphAbatt",
    GraphAcp: "GraphAcp",
    GraphBreakPos: "GraphBreakPos",
    GraphEct: "GraphEct",
    GraphGearPos: "GraphGearPos",
    GraphMotor123Current: "GraphMotor123Current",
    GraphMotor123RPM: "GraphMotor123RPM",
    GraphMotor123Volt: "GraphMotor123Volt",
    GraphRangeToGo: "GraphRangeToGo",
    GraphSoc: "GraphSoc",
    GraphSpeed: "GraphSpeed",
    GraphStearing: "GraphStearing",
    GraphVoltBatt: "GraphVoltBatt",
}